# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-25 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cmdb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obj_type', models.CharField(max_length=300)),
                ('device_number', models.CharField(max_length=300)),
                ('ip', models.CharField(max_length=300)),
                ('device_status', models.CharField(max_length=300)),
                ('device_mod', models.CharField(max_length=300)),
                ('device_locate', models.CharField(max_length=300)),
                ('admin', models.CharField(max_length=300)),
                ('product_tree', models.CharField(max_length=300)),
                ('isp', models.CharField(max_length=300)),
                ('current_user', models.CharField(max_length=300)),
                ('product', models.CharField(max_length=300)),
                ('upstream_device', models.CharField(max_length=300)),
                ('downstream_device', models.CharField(max_length=300)),
                ('requirement', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='testcase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=300)),
                ('name2', models.CharField(max_length=300)),
                ('name3', models.CharField(max_length=300)),
            ],
        ),
    ]
